<a href="https://colab.research.google.com/github/mmilanquery55-dev/NumPy-Tutorial-/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.2


Creating Arrays

In [3]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [4]:
print(type(list1))

<class 'list'>


In [5]:
# 1D array
arr_list1=np.array(list1)
print(arr_list1)

[1 2 3]


In [6]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [7]:
# ndim => n-dimensional
print(arr_list1.ndim)

1


In [8]:
# 2D array
list1=[1,2,3]
list2=[4,5,6]
arr_list2=np.array([list1,list2])
print(arr_list2)


[[1 2 3]
 [4 5 6]]


In [9]:
# ndim => n-dimensional
print(arr_list2.ndim)

2


In [10]:
# 3D array
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list3=np.array([[list1,list2,list3]])
print(arr_list3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [11]:
# ndim => n-dimensional
print(arr_list3.ndim)

3


numpy array attributes

In [12]:
array1=np.array([22,33,44])
print(array1)
print("n-dimesnional",array1.ndim)
print("Shape",array1.shape)
print("dtype",array1.dtype)
print("Size",array1.size)

[22 33 44]
n-dimesnional 1
Shape (3,)
dtype int64
Size 3


In [13]:
array2=np.array([[1,2,3],[5,6,7]])
print(array2)
print("n-dimesnional",array2.ndim)
print("Shape",array2.shape)
print("dtype",array2.dtype)
print("Size",array2.size)

[[1 2 3]
 [5 6 7]]
n-dimesnional 2
Shape (2, 3)
dtype int64
Size 6


In [14]:
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3)
print("n-dimesnional",array3.ndim)
print("Shape",array3.shape)
print("dtype",array3.dtype)
print("Size",array3.size)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
n-dimesnional 3
Shape (1, 3, 3)
dtype int64
Size 9


Array initialization methods

In [15]:
# Zeros array
zero_arr=np.zeros((3,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# ones array
ones_arr=np.ones((2,3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# Full array
full_arr=np.full((2,3),5)
print(full_arr)

[[5 5 5]
 [5 5 5]]


In [18]:
# Identity Matrix  -> It is always 3 rows and
# 3 columns and it's dimensions are 1 and other values is 0 .
id_arr=np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# empty array
print(np.empty(2))


[4.94065646e-324 6.54524471e-310]


In [20]:
# evenly spaced array
print(np.arange(1,10,2))

[1 3 5 7 9]


In [21]:
# Specific number of equally (spaced) values between a range
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [22]:
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [23]:
# random values array-float
r_arr=np.random.rand(3,2)
print(r_arr)

[[0.48226506 0.37634586]
 [0.81753406 0.68939331]
 [0.75538282 0.35591621]]


In [24]:
# random values array-int
r_arr=np.random.randint(1,100,(3,3))
print(r_arr)

[[56 73 91]
 [13 30 13]
 [77 66 14]]


In [25]:
r_arr=np.random.randint(1,50,(3,3))
print(r_arr)

[[13  3 21]
 [35 16 43]
 [33 12 29]]


Array Indexing and Slicing

In [26]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [27]:
print(a[0])

1


In [28]:
print(a[4])

5


In [29]:
print(a[-2])

4


In [30]:
print(a[-1])

5


In [31]:
print(a[-5])

1


In [32]:
# Slicing
# array[start:stop:step]
# stop - index, that is not inlcuded in output

b=np.array([1,2,3,4,5,6,7,8])
print(b)

[1 2 3 4 5 6 7 8]


In [33]:
print(b[0:3])

[1 2 3]


In [34]:
print(b[5])

6


In [35]:
print(b[-1])

8


In [36]:
print(b[-3:])

[6 7 8]


In [37]:
print(b[-2:])

[7 8]


In [38]:
print(b[0:8:2])

[1 3 5 7]


In [39]:
print(b[0::])

[1 2 3 4 5 6 7 8]


In [40]:
print(b[0::3])

[1 4 7]


In [41]:
print(b[::3])

[1 4 7]


In [42]:
print(b[::4])

[1 5]


In [43]:
print(b[::6])

[1 7]


In [44]:
# 2D array slicing
import numpy as np
array1 = np.array([[1,2,3],[5,6,7]])
print(array1)
print(array1.ndim)

[[1 2 3]
 [5 6 7]]
2


In [45]:
print(array1[0][0])
print(array1[0][1])
print(array1[0][2])
print(array1[1][0])
print(array1[1][1])
print(array1[1][2])

1
2
3
5
6
7


In [46]:
print(array1[1])
print(array1[1:])
print(array1)

[5 6 7]
[[5 6 7]]
[[1 2 3]
 [5 6 7]]


In [47]:
print(array1[:,0])
print(array1[1:,0])
print(array1[0:,2])
print(array1[0:,1])
print(array1[1:,1])
print(array1[1:,2])

[1 5]
[5]
[3 7]
[2 6]
[6]
[7]


In [48]:
arr3=np.array([[1,2,3],
              [3,4,5],
              [7,8,9]])
print(arr3)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [49]:
print(arr3.ndim)
print(arr3.shape)

2
(3, 3)


In [50]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[3 4 5]
[7 8 9]


In [51]:
print(arr3[0][2])
print(arr3[1][2])
print(arr3[2][1])

3
5
8


In [52]:
print(arr3[1])
print(arr3[:,1])

[3 4 5]
[2 4 8]


In [53]:
print(arr3[::2,0])

[1 7]


In [54]:
# Slicing on columns
print(arr3[::, 1:2])
# Slicing on rows and columns
print(arr3[2::, 1:2])

[[2]
 [4]
 [8]]
[[8]]


Array reshaping ans Flattening

In [55]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [56]:
reshaped=arr1.reshape((5,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [57]:
arr2=np.array([4,5,6])
print(arr2)

[4 5 6]


In [58]:
reshaped=arr2.reshape((3,1))
print(reshaped)

[[4]
 [5]
 [6]]


In [59]:
arr3=np.array([1,2,3,4,5,6])
print(arr3)

[1 2 3 4 5 6]


In [60]:
reshaped=arr3.reshape((2,3))
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [61]:
arr4=np.array([1,2,3,4,5,6,7,8,9])
print(arr3)

[1 2 3 4 5 6]


In [62]:
reshaped=arr4.reshape((3,3))
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
# flatten -> it makes a 2D or 3D array convert into 1D array
print(reshaped.flatten())

[1 2 3 4 5 6 7 8 9]


Array Stacking  and Spliting

In [64]:
# Stacking -> 1.Vertical stacking , 2. Horizontal Stacking
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.vstack((a,b)))
print(np.hstack((a,b)))



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [65]:
#  Split -> in simple term split is using for breaking the array
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [66]:
print(np.hsplit(c,3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [67]:
# Horizontal Split
split=np.hsplit(c,3)
for s in split:
  print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [68]:
# Vertical Split
d=np.array([[1,2,3],[4,5,6]])
print(d)


[[1 2 3]
 [4 5 6]]


In [69]:
split=np.vsplit(d,2)
print(split)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [70]:
split = np.vsplit(d,2)
for s in split:
  print(s)

[[1 2 3]]
[[4 5 6]]


Mathematical Operations

In [71]:
a=np.array([10,20,30,40,50])
print(a)


[10 20 30 40 50]


In [72]:
print(a+10)
print(a-20)
print(a*2)
print(a/10)
print(a%3)

[20 30 40 50 60]
[-10   0  10  20  30]
[ 20  40  60  80 100]
[1. 2. 3. 4. 5.]
[1 2 0 1 2]


In [73]:
b=np.array([1,4,9])
print(b)

[1 4 9]


In [74]:
print(np.square(b))
print(np.sqrt(b))
# sqrt means Square Root

[ 1 16 81]
[1. 2. 3.]


In [75]:
print(np.sin(b))
print(np.tan(b))
print(np.cos(b))


[ 0.84147098 -0.7568025   0.41211849]
[ 1.55740772  1.15782128 -0.45231566]
[ 0.54030231 -0.65364362 -0.91113026]


Mathematical Operations on Multiple Arrays

In [76]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [77]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]


In [78]:
# dot product -> fistly multipling array a and array b each
# other and then adding the total value
# which is comes in multiply a and b lastly show the value

print(np.dot(a,b))

32


In [79]:
# Transpose -> T ,Here
# transpose makes row to columns and columns to row

t=np.array([[1,2,3],[4,5,6]])
print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Statistical Functions  

In [80]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.sum(a))

[[1 2 3]
 [4 5 6]]
21


In [81]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


Array Comparison

In [82]:
a=np.array([1,2,3])
b=np.array([1,4,5])
print(a)
print(b)


[1 2 3]
[1 4 5]


In [83]:
print(a == b)
print(a > b)
print(a < b)
print(np.array_equal(a,b))


[ True False False]
[False False False]
[False  True  True]
False


**Broadcasting**

In [84]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5])
print(a+b)

[6 7 8 9]


In [85]:
c=np.array([[1,2,3],[5,6,7]])
d=np.array([10,15,20])
print(c+d)

[[11 17 23]
 [15 21 27]]


Handling Null Values (Handling with nan and inf)

In [86]:
data1=np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [87]:
print(np.isnan(data1))

[False False  True False False]


In [88]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


Save and Load arrays

In [89]:
arr=np.array([1,3,4])
print(arr)
np.save('my_arr.npy',arr)


[1 3 4]


In [90]:
loaded_arr=np.load('my_arr.npy')
print(loaded_arr)

[1 3 4]
